Repository wenzhixin/bootstrap-table, pull requests merged in 2018-09, with the labels that each got.

#3968 Fixes
  src/bootstrap-table.js
  src/extensions/cookie/bootstrap-table-cookie.js
  src/extensions/filter-control/README.md
  src/extensions/filter-control/bootstrap-table-filter-control.js
Labels: in progress

#3973 New version of bootstrap-table-resizable v2.0.0
  package-lock.json
  src/extensions/resizable/README.md
  src/extensions/resizable/bootstrap-table-resizable.js
Labels: in progress

#3975 fix "check" function using wrong variable name
  src/bootstrap-table.js
Labels: needs example

#3572 add the bootstrap-table-addrbar extension
  src/extensions/addrbar/bootstrap-table-addrbar.js
  src/extensions/addrbar/demo.html
  src/extensions/addrbar/demo2.html
  src/extensions/addrbar/readme.md
Labels: awaiting reply, needs example
