Repository wenzhixin/bootstrap-table, pull requests merged in 2019-03, with the labels that each got.

#4209 Feature/update locale
  src/bootstrap-table.js
  src/locale/bootstrap-table-af-ZA.js
  src/locale/bootstrap-table-ar-SA.js
  src/locale/bootstrap-table-ca-ES.js
  src/locale/bootstrap-table-cs-CZ.js
  src/locale/bootstrap-table-da-DK.js
  src/locale/bootstrap-table-de-DE.js
  src/locale/bootstrap-table-el-GR.js
  src/locale/bootstrap-table-en-US.js
  src/locale/bootstrap-table-en-US.js.template
  src/locale/bootstrap-table-es-AR.js
  src/locale/bootstrap-table-es-CL.js
  src/locale/bootstrap-table-es-CR.js
  src/locale/bootstrap-table-es-ES.js
  src/locale/bootstrap-table-es-MX.js
  src/locale/bootstrap-table-es-NI.js
  src/locale/bootstrap-table-es-SP.js
  src/locale/bootstrap-table-et-EE.js
  src/locale/bootstrap-table-eu-EU.js
  src/locale/bootstrap-table-fa-IR.js
  src/locale/bootstrap-table-fi-FI.js
  src/locale/bootstrap-table-fr-BE.js
  src/locale/bootstrap-table-fr-FR.js
  src/locale/bootstrap-table-he-IL.js
  src/locale/bootstrap-table-hr-HR.js
  src/locale/bootstrap-table-hu-HU.js
  src/locale/bootstrap-table-id-ID.js
  src/locale/bootstrap-table-it-IT.js
  src/locale/bootstrap-table-ja-JP.js
  src/locale/bootstrap-table-ka-GE.js
  src/locale/bootstrap-table-ko-KR.js
  src/locale/bootstrap-table-ms-MY.js
  src/locale/bootstrap-table-nb-NO.js
  src/locale/bootstrap-table-nl-NL.js
  src/locale/bootstrap-table-pl-PL.js
  src/locale/bootstrap-table-pt-BR.js
  src/locale/bootstrap-table-pt-PT.js
  src/locale/bootstrap-table-ro-RO.js
  src/locale/bootstrap-table-ru-RU.js
  src/locale/bootstrap-table-sk-SK.js
  src/locale/bootstrap-table-sv-SE.js
  src/locale/bootstrap-table-th-TH.js
  src/locale/bootstrap-table-tr-TR.js
  src/locale/bootstrap-table-uk-UA.js
  src/locale/bootstrap-table-ur-PK.js
  src/locale/bootstrap-table-uz-Latn-UZ.js
  src/locale/bootstrap-table-vi-VN.js
  src/locale/bootstrap-table-zh-CN.js
  src/locale/bootstrap-table-zh-TW.js
Labels: In progress

#4225 rerender the table on save data
  src/extensions/editable/bootstrap-table-editable.js
Labels: In progress

#4202 Adding line to clear values from filter control
  src/extensions/filter-control/bootstrap-table-filter-control.js
Labels: In progress

#4218 Impoved Search - Added check for comperations (<,>,<=,=<,>=,=>)
  site/docs/api/table-options.md
  src/bootstrap-table.js
Labels: feature

#4222 check if queryParams is a function to prevent critical issues
  src/extensions/multiple-sort/bootstrap-table-multiple-sort.js
Labels: multiple-sort

#4229 Added row index as parameter for the onEditableSave event
  site/docs/extensions/editable.md
  src/extensions/editable/bootstrap-table-editable.js
Labels: editable

#4231 updated the code guidelines (use semicolons => dont use semicolons)
  CONTRIBUTING.md
Labels: In progress

#4236 fix toolbar dropdown button border
  src/themes/bulma/bootstrap-table-bulma.scss
  src/themes/foundation/bootstrap-table-foundation.js
  src/themes/foundation/bootstrap-table-foundation.scss
  src/themes/materialize/bootstrap-table-materialize.js
Labels: css

#4238 Improved functions showColumn and hideColumn
  site/docs/api/methods.md
  src/bootstrap-table.js
Labels: feature, js

#4232 Added post footer event
  site/docs/api/events.md
  src/bootstrap-table.js
Labels: feature

#4240 improved scrollTo function to allow units (new unit is rows)
  site/docs/api/methods.md
  src/bootstrap-table.js
Labels: In progress

#4244 Improved documentation of the table url attribute
  site/docs/api/table-options.md
Labels: In progress, docs

#4242 Added documentation for checkboxEnabled
  site/docs/api/column-options.md
Labels: In progress, docs

#4241 Added ability to handle booleans and simplify code
  src/extensions/filter-control/bootstrap-table-filter-control.js
Labels: In progress, filter-control

#4220 Use the internal onColumnSearch function to prevent event issues
  src/extensions/filter-control/bootstrap-table-filter-control.js
Labels: filter-control

#3647 Add cell input extension
  src/extensions/cell-input/README.md
  src/extensions/cell-input/bootstrap-table-cell-input.css
  src/extensions/cell-input/bootstrap-table-cell-input.js
  src/extensions/cell-input/extension.json
Labels: In progress, needs documentation

#4245 Moving cell-input.md docs to correct folder
  site/docs/extensions/cell-input.md
  src/extensions/cell-input/README.md
Labels: In progress

#4219 Detailview per column
  site/docs/api/column-options.md
  site/docs/api/table-options.md
  src/bootstrap-table.js
Labels: In progress, feature, needs documentation

#4226 Show count of not filtered rows
  site/docs/api/table-options.md
  src/bootstrap-table.js
  src/locale/bootstrap-table-af-ZA.js
  src/locale/bootstrap-table-ar-SA.js
  src/locale/bootstrap-table-ca-ES.js
  src/locale/bootstrap-table-cs-CZ.js
  src/locale/bootstrap-table-da-DK.js
  src/locale/bootstrap-table-de-DE.js
  src/locale/bootstrap-table-el-GR.js
  src/locale/bootstrap-table-en-US.js
  src/locale/bootstrap-table-es-AR.js
  src/locale/bootstrap-table-es-CL.js
  src/locale/bootstrap-table-es-CR.js
  src/locale/bootstrap-table-es-ES.js
  src/locale/bootstrap-table-es-MX.js
  src/locale/bootstrap-table-es-NI.js
  src/locale/bootstrap-table-es-SP.js
  src/locale/bootstrap-table-et-EE.js
  src/locale/bootstrap-table-eu-EU.js
  src/locale/bootstrap-table-fa-IR.js
  src/locale/bootstrap-table-fi-FI.js
  src/locale/bootstrap-table-fr-BE.js
  src/locale/bootstrap-table-fr-FR.js
  src/locale/bootstrap-table-he-IL.js
  src/locale/bootstrap-table-hr-HR.js
  src/locale/bootstrap-table-hu-HU.js
  src/locale/bootstrap-table-id-ID.js
  src/locale/bootstrap-table-it-IT.js
  src/locale/bootstrap-table-ja-JP.js
  src/locale/bootstrap-table-ka-GE.js
  src/locale/bootstrap-table-ko-KR.js
  src/locale/bootstrap-table-ms-MY.js
  src/locale/bootstrap-table-nb-NO.js
  src/locale/bootstrap-table-nl-NL.js
  src/locale/bootstrap-table-pl-PL.js
  src/locale/bootstrap-table-pt-BR.js
  src/locale/bootstrap-table-pt-PT.js
  src/locale/bootstrap-table-ro-RO.js
  src/locale/bootstrap-table-ru-RU.js
  src/locale/bootstrap-table-sk-SK.js
  src/locale/bootstrap-table-sv-SE.js
  src/locale/bootstrap-table-th-TH.js
  src/locale/bootstrap-table-tr-TR.js
  src/locale/bootstrap-table-uk-UA.js
  src/locale/bootstrap-table-ur-PK.js
  src/locale/bootstrap-table-uz-Latn-UZ.js
  src/locale/bootstrap-table-vi-VN.js
  src/locale/bootstrap-table-zh-CN.js
  src/locale/bootstrap-table-zh-TW.js
Labels: In progress, js

#4230 Improved the filterBy function with OR condition and custom filter algorythm
  site/docs/api/methods.md
  src/bootstrap-table.js
Labels: In progress, feature, js

#4251 Dont bind the click event on page seperators
  src/bootstrap-table.js
Labels: In progress

#4250 Reorder the column options and update column options docs
  site/docs/api/column-options.md
  src/bootstrap-table.js
Labels: js

#4252 Added column field to formatters function
  src/bootstrap-table.js
Labels: In progress

#4253 Also add classes and style from cellStyle option/function
  src/bootstrap-table.js
Labels: In progress

#4262 Prevent line break to table header "cell"
  src/themes/theme.scss
Labels: In progress
