Repository wenzhixin/bootstrap-table, pull requests merged in 2019-01, with the labels that each got.

#4094 Filter control cookies improvements
  .eslintrc.js
  docs/_i18n/en/documentation/table-options.md
  docs/_i18n/es/documentation/table-options.md
  docs/_i18n/zh-cn/documentation/table-options.md
  package.json
  src/bootstrap-table.css
  src/bootstrap-table.js
  src/extensions/cookie/bootstrap-table-cookie.js
  src/extensions/filter-control/bootstrap-table-filter-control.js
Labels: In progress

#4114 Bootstrap-Table Pipeline extension feature request
  src/extensions/pipeline/LICENSE
  src/extensions/pipeline/README.md
  src/extensions/pipeline/bootstrap-table-pipeline.js
  src/extensions/pipeline/extension.json
Labels: needs example

#4109 bootstrap-table-group-by header formatter
  site/docs/extensions/group-by-v2.md
  src/extensions/group-by-v2/bootstrap-table-group-by.js
Labels: needs documentation, needs example

#4123 Adding pageNumber to the server side pagination
  CHANGELOG.md
  src/bootstrap-table.js
Labels: In progress

#4137 Rewrite accent-neutralise extension to ES6
  CHANGELOG.md
  site/docs/extensions/accent-neutralise.md
  site/docs/extensions/addrbar.md
  src/bootstrap-table.js
  src/extensions/accent-neutralise/bootstrap-table-accent-neutralise.js
  src/extensions/addrbar/bootstrap-table-addrbar.js
  src/extensions/addrbar/demo.html
  src/extensions/addrbar/demo2.html
  src/extensions/cookie/bootstrap-table-cookie.js
  src/extensions/filter-control/bootstrap-table-filter-control.js
Labels: In progress

#4131 Feature/upgrade
  .gitignore
  CHANGELOG.md
  package.json
  site/docs/api/table-options.md
  src/bootstrap-table.css
  src/bootstrap-table.js
  src/bootstrap-table.scss
Labels: In progress

#4142 Fix auto-refresh icon
  src/extensions/auto-refresh/bootstrap-table-auto-refresh.js
Labels: In progress
