Repository wenzhixin/bootstrap-table, pull requests merged in 2019-12, with the labels that each got.

#4737 Feature/header style
  site/docs/api/table-options.md
  src/bootstrap-table.js
  src/constants/index.js
Labels: feature

#4739 Fixed customSearch return empty array bug
  src/bootstrap-table.js
Labels: js

#4729 Update bootstrap-table-cookie.js
  src/bootstrap-table.js
  src/extensions/cookie/bootstrap-table-cookie.js
  src/extensions/filter-control/bootstrap-table-filter-control.js
Labels: needs example

#4766 Supported build cross platform
  .stylelintrc
  package.json
  src/extensions/cell-input/bootstrap-table-cell-input.scss
  src/extensions/filter-control/bootstrap-table-filter-control.scss
  src/extensions/fixed-columns/bootstrap-table-fixed-columns.scss
  src/extensions/group-by-v2/bootstrap-table-group-by.scss
  src/extensions/page-jump-to/bootstrap-table-page-jump-to.scss
  src/extensions/reorder-rows/bootstrap-table-reorder-rows.scss
  src/extensions/sticky-header/bootstrap-table-sticky-header.scss
  src/themes/_theme.scss
  src/themes/bootstrap/_variables.scss
  src/themes/bulma/_variables.scss
  src/themes/foundation/_variables.scss
  src/themes/materialize/_variables.scss
  src/themes/semantic/_variables.scss
Labels: build
