Repository wenzhixin/bootstrap-table, pull requests merged in 2019-04, with the labels that each got.

#4259 Added option to hide the show/hide icons for the detail view
  site/docs/api/methods.md
  site/docs/api/table-options.md
  src/bootstrap-table.js
Labels: In progress, feature, js

#4268 Feature/performance improve
  src/bootstrap-table.js
  src/constants/index.js
  src/utils/index.js
  src/virtual-scroll/index.js
Labels: In progress

#4277 added missing documentation for the onCollapseRow event
  site/docs/api/events.md
Labels: In progress

#4280 Renamed table option maintainSelected
  site/docs/api/table-options.md
  src/bootstrap-table.js
  src/constants/index.js
Labels: In progress

#4281 Remove group by since it has a jquery dependency plugin
  site/docs/extensions/group-by.md
  src/extensions/group-by/bootstrap-table-group-by.css
  src/extensions/group-by/bootstrap-table-group-by.js
  src/extensions/group-by/extension.json
Labels: In progress

#4279 Only export table header
  src/extensions/export/bootstrap-table-export.js
Labels: In progress, reviewed

#4278 Feature/extensions
  site/_data/core-team.yml
  site/docs/api/table-options.md
  site/docs/extensions/addrbar.md
  src/bootstrap-table.js
  src/constants/index.js
  src/extensions/addrbar/bootstrap-table-addrbar.js
  src/extensions/auto-refresh/bootstrap-table-auto-refresh.js
  src/extensions/copy-rows/bootstrap-table-copy-rows.js
  src/extensions/export/bootstrap-table-export.js
  src/extensions/filter-control/bootstrap-table-filter-control.js
  src/extensions/print/bootstrap-table-print.js
  src/extensions/sticky-header/bootstrap-table-sticky-header.js
  src/extensions/toolbar/bootstrap-table-toolbar.js
  src/extensions/tree-column/bootstrap-table-tree-column.css
  src/extensions/tree-column/bootstrap-table-tree-column.js
  src/extensions/tree-column/bootstrap-table-tree-column.less
  src/extensions/tree-column/extension.json
  src/extensions/tree-column/icon.png
  src/themes/bulma/bootstrap-table-bulma.js
  src/themes/foundation/bootstrap-table-foundation.js
  src/themes/foundation/bootstrap-table-foundation.scss
  src/themes/materialize/bootstrap-table-materialize.js
  src/themes/materialize/bootstrap-table-materialize.scss
  src/themes/semantic/bootstrap-table-semantic.js
  src/themes/semantic/bootstrap-table-semantic.scss
  src/themes/theme.scss
Labels: extension, js

#4288 Fix issue 4072
  site/docs/api/column-options.md
  src/bootstrap-table.js
Labels: In progress

#4290 fix #4289: Fixed columns title error
  src/bootstrap-table.js
Labels: js

#4295 Fix table options bug and add examples
  site/docs/api/table-options.md
  src/bootstrap-table.js
  src/constants/index.js
  src/locale/bootstrap-table-af-ZA.js
  src/locale/bootstrap-table-ar-SA.js
  src/locale/bootstrap-table-ca-ES.js
  src/locale/bootstrap-table-cs-CZ.js
  src/locale/bootstrap-table-da-DK.js
  src/locale/bootstrap-table-de-DE.js
  src/locale/bootstrap-table-el-GR.js
  src/locale/bootstrap-table-en-US.js
  src/locale/bootstrap-table-es-AR.js
  src/locale/bootstrap-table-es-CL.js
  src/locale/bootstrap-table-es-CR.js
  src/locale/bootstrap-table-es-ES.js
  src/locale/bootstrap-table-es-MX.js
  src/locale/bootstrap-table-es-NI.js
  src/locale/bootstrap-table-es-SP.js
  src/locale/bootstrap-table-et-EE.js
  src/locale/bootstrap-table-eu-EU.js
  src/locale/bootstrap-table-fa-IR.js
  src/locale/bootstrap-table-fi-FI.js
  src/locale/bootstrap-table-fr-BE.js
  src/locale/bootstrap-table-fr-FR.js
  src/locale/bootstrap-table-he-IL.js
  src/locale/bootstrap-table-hr-HR.js
  src/locale/bootstrap-table-hu-HU.js
  src/locale/bootstrap-table-id-ID.js
  src/locale/bootstrap-table-it-IT.js
  src/locale/bootstrap-table-ja-JP.js
  src/locale/bootstrap-table-ka-GE.js
  src/locale/bootstrap-table-ko-KR.js
  src/locale/bootstrap-table-ms-MY.js
  src/locale/bootstrap-table-nb-NO.js
  src/locale/bootstrap-table-nl-NL.js
  src/locale/bootstrap-table-pl-PL.js
  src/locale/bootstrap-table-pt-BR.js
  src/locale/bootstrap-table-pt-PT.js
  src/locale/bootstrap-table-ro-RO.js
  src/locale/bootstrap-table-ru-RU.js
  src/locale/bootstrap-table-sk-SK.js
  src/locale/bootstrap-table-sv-SE.js
  src/locale/bootstrap-table-th-TH.js
  src/locale/bootstrap-table-tr-TR.js
  src/locale/bootstrap-table-uk-UA.js
  src/locale/bootstrap-table-ur-PK.js
  src/locale/bootstrap-table-uz-Latn-UZ.js
  src/locale/bootstrap-table-vi-VN.js
  src/locale/bootstrap-table-zh-CN.js
  src/locale/bootstrap-table-zh-TW.js
Labels: In progress, example, js

#4314 Adding filterOrderBy column option
  site/docs/extensions/filter-control.md
  src/bootstrap-table.js
  src/extensions/filter-control/bootstrap-table-filter-control.js
  src/utils/index.js
Labels: In progress

#4313 Fix #4282: updated treegrid
  src/bootstrap-table.js
  src/extensions/export/bootstrap-table-export.js
  src/extensions/treegrid/bootstrap-table-treegrid.js
Labels: reviewed, treegrid

#4315 Fix rowStyle overwrite bug
  src/extensions/treegrid/bootstrap-table-treegrid.js
Labels: In progress, treegrid

#4328 Copy the dir attribute
  src/extensions/print/bootstrap-table-print.js
Labels: In progress

#4336 Implement a version number
  src/bootstrap-table.js
  src/constants/index.js
Labels: In progress
